[volume]
downsample = [2, 2, 0]
resolution = [16, 16, 40]

[model]
block_size = [33, 33, 13]
v_true = 0.95
v_false = 0.05
t_move = 0.9
move_check_thickness = 1

[network]
factory = 'diluvian.diluvian.make_flood_fill_network'
num_modules = 8
convolution_dim = [3, 3, 3]
convolution_filters = 32
output_activation = "sigmoid"

[optimizer]
class = "SGD"
lr = 0.001
momentum = 0.5
nesterov = true

[training]
gpu_batch_size = 32
num_gpus = 1
training_size = 256
validation_size = 32
simple_train_epochs = 1
total_epochs = 2
# fill_factor_bins = [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.075,
#                     0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
partitions = [1, 1, 2]
training_partition = [0, 0, 0]
validation_partition = [0, 0, 1]
patience = 20
