[volume]
downsample = [1, 1, 0]
resolution = [8, 8, 40]

[model]
block_size = [65, 65, 13]
v_true = 0.95
v_false = 0.05
t_move = 0.9

[network]
num_modules = 8
convolution_dim = [5, 5, 3]

[optimizer]
learning_rate = 0.01
momentum = 0.9
nesterov_momentum = true

[training]
batch_size = 32
training_size = 256
validation_size = 32
# training_size = 4096
# validation_size = 1024
simple_train_epochs = 1
total_epochs = 2
